### ISSUE TITLE
OtelAxumLayer and OtelInresponseLayer don't work with opentelemetry_otlp exporter

### ISSUE THREAD

**Issue by npuichigo** [davidB/tracing-opentelemetry-instrumentation-sdk#102]
I switched from `opentelemetry-jaeger`/`opentelemetry-zipkin` to `opentelemetry-otlp`, and these two middlewares are no longer work for me. Previously, I can get trace id in response header for user debugging, but now it's missing.

```
let tracer = opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_endpoint("http://localhost:4317"),
        )
        .with_trace_config(sdktrace::config().with_resource(Resource::new(vec![
            opentelemetry::KeyValue::new("service.name", "kakashi"),
        ])))
        .install_batch(runtime::Tokio).unwrap();
let tracer_layer = tracing_opentelemetry::layer().with_tracer(tracer);
```

https://github.com/open-telemetry/opentelemetry-rust/issues/1338

**Comment by npuichigo** [comment]
Sorry, I missed to set propagator. After replacing `global::set_text_map_propagator(opentelemetry_jaeger::Propagator::new());` with `global::set_text_map_propagator(TraceContextPropagator::new());`.

The response trace id became something like `traceparent: 00-75950901f5529540ee4c93f55c5b273a-ea2176fd6996905a-01`, how can I customize the different format? I remember Jaeger uses uber-id.

**Comment by npuichigo** [comment]
Close since I missed to pass proper propagater.

**Comment by lcmgh** [comment]
@npuichigo how did your fix look like?
