### ISSUE TITLE
New opentelemetry releases unsupported

### ISSUE THREAD

**Issue by beanow-at-crabnebula** [davidB/tracing-opentelemetry-instrumentation-sdk#108]
The `0.21.x` releases are up: https://github.com/open-telemetry/opentelemetry-rust/releases
Upgrading those crates will cause things like context propagation to break.

**Comment by davidB** [comment]
- Having only one version of opentelemetry is supported, because some globals (propagators, ...) are static value
- Upgrading crates on this repo is in progress (breaking changes on the opentelemetry crates require some adaptation).

**Comment by davidB** [comment]
version `0.15` was released for opentelemetry `0.21`
