### ISSUE TITLE
tracing level for http integrations is below info

### ISSUE THREAD

**Issue by rbtcollins** [davidB/tracing-opentelemetry-instrumentation-sdk#126]
We use the `max_level_info` feature from the tracing crate to ensure that we don't end up with terabytes of debug or trace spans in production.

With that set, if we try to set `otel::tracing=trace`  a warning is emitted:

```
warning: some trace filter directives would enable traces that are disabled statically
note: `otel::tracing=trace` would enable the TRACE level for the `otel::tracing` target
note: `otel::setup=debug` would enable the DEBUG level for the `otel::setup` target
note: the static max level is `info`
help: to enable DEBUG logging, remove the `max_level_info` feature from the `tracing` crate
```

The side effect here is two fold:

1. the traceparent in response layer doesn't work, because there is no active context - because the opentel context short-circuits to None when there is no active span
2. HTTP routes that are not explicitly annotated with `[#instrument]` do not get any instrumentation at all.

#97 seems to be in a similar place, question wise.

Creating a trace context from an HTTP request should not be given a [level](https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/blob/36cc782f19569c4b2aa3611d0a9db376a485bc90/tracing-opentelemetry-instrumentation-sdk/src/http/http_server.rs#L13) of `trace`, because it isn't some internal implementation detail - it is the fundamental building block of distributed trace propogation.

I'm more than happy to provide a patch - I suggest info_span!, but a higher priority would also work. (edit: see #127 ) - needed to put that together to fix our systems

In terms of user interface - it is still possible to turn such a level on and of granularly - set otel::tracing to error, and it would be off, for instance.

**Comment by davidB** [comment]
I'll take a look at the PR and do some tests. And what happens for the team using the `max_level_warn` feature?

For example, in my team, the default level for production/live is a warning to reduce noisy useless info, with don't use any `max_level_...` to be able to temporarily decrease the level via environment variable without the need to rebuild, ci, cd,...).

IMHO `trace` level is the perfect level for traces (same name) ;-)

**Comment by rbtcollins** [comment]
There's an argument to be made that having levels on traces is a broken concept - thats the one minitrace makes - https://www.reddit.com/r/rust/comments/1abbyc9/announcing_minitrace_06_a_modern_alternative_of/ 

I'm going to start a discussion internally about whether we really need that feature flag on tracing, it does have some significant downsides!

A team using `max_level_warn` may indeed come back and ask for the abililty to control the level that the instrumentation library traces at; I don't think they would ask for the level to be changed, because `info` is documented as being a common practice for production: https://docs.rs/tracing/latest/tracing/struct.Level.html#filtering

> When running in production, only [INFO](https://docs.rs/tracing/latest/tracing/struct.Level.html#associatedconstant.INFO)-level and lower traces might be enabled. Libraries may include very verbose diagnostics at the [DEBUG](https://docs.rs/tracing/latest/tracing/struct.Level.html#associatedconstant.DEBUG) and/or [TRACE](https://docs.rs/tracing/latest/tracing/struct.Level.html#associatedconstant.TRACE) levels. Applications using those libraries typically chose to ignore those traces.

To me the level 'trace' in tracing is a false friend with the verb to-trace, much more important are the semantics e.g. in my head:

* ERROR someone responsible for the system MUST know about this, the system is misbehaving
* WARN  someone responsible for the system SHOULD know about this, the system is likely misbehaving
* INFO if someone is looking at the system, this will be helpful most of the time
* DEBUG when something is considered broken this will be helpful, but costs too much to generate/export to have on always
* TRACE like DEBUG but more, and may include internals of protocol statemachines and other details that are both very reliable and super high volume

This is at a cross-section in intent to trace propogation into and out of a server, which is I think the argument minitrace make: it doesn't which verbosity level is in use, the distributed traces need to be connected end to end, or else they don't make up a 'trace'.

Perhaps raising these propogation spans up to ERROR would be the best thing :)

**Comment by davidB** [comment]
Thanks for the link, information, and the PR. I'll try an approach with feature flags to let users choose the level, if possible.

**Comment by purkhusid** [comment]
Hitting the same issue. I think it makes sense to have the default level set to `info` makes more sense. E.g. in some workloads it makes sense to trace every single request. Also, the `trace` level is used fairly widely in Rust crates as a setting that includes some very verbose logging/tracing.

**Comment by davidB** [comment]
since version 0.18.1 of tracing-opentelemetry-instrumentation-sdk, you can enable the feature `tracing_level_info` to use info as level for span.
