### ISSUE TITLE
Why is the trace-id not propagated to the response?

### ISSUE THREAD

**Issue by holicc** [davidB/tracing-opentelemetry-instrumentation-sdk#149]
dependencies: 
```
opentelemetry = { version = "0.23", features = ["trace"] }
opentelemetry-otlp = { version = "0.16", default-features = false, features = [
    "reqwest-client",
    "reqwest-rustls",
    "http-proto",
    "tls",
] }
axum-tracing-opentelemetry = "0.19.0"
init-tracing-opentelemetry = { version = "0.19.0", features = [
    "otlp",
    "tracing_subscriber_ext",
] }
tracing-opentelemetry-instrumentation-sdk = "0.19.0"
```

router layer:

![image](https://github.com/user-attachments/assets/fb1fcdda-c6ad-4eb6-9fe5-1e5f9e9d64f1)

request and response:

![image](https://github.com/user-attachments/assets/58798a4b-0d19-4228-8087-dd4ab85bedc0)

**Comment by aimericsr** [comment]
In Axum, layers are wrapping each others. So here, when a request comes in, OtelInResponseLayer is called first and after OtelAxumLayer. But when your server send the response, it's OtelAxumLayer and then OtelInResponseLayer. But the layer that created the span is OtelAxumLayer. So the span is already dropped when OtelInResponseLayer try to insert trace-id into the HTTP response headers, so there are no more opentelemtry context. You just need to invert the order of these two layers and it should fix it.

**Comment by holicc** [comment]
No, the reason is not the order of the layers. The framework did not extract the `trace-id` from the request because OpenTelemetry only propagates `tracecontext` by default. We should use `traceparent` to pass the information. Additionally, we should not invert the order of the layers, as it would prevent our `traceparent` from being passed down correctly. 

https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/blob/b64946e5c37fdd0557c43af1286533fac2ac6853/axum-tracing-opentelemetry/src/middleware/trace_extractor.rs#L132
