### ISSUE TITLE
Support `tonic` 0.12

### ISSUE THREAD

**Issue by 23Skidoo** [davidB/tracing-opentelemetry-instrumentation-sdk#150]
`tonic` 0.12 is now out, but `tonic-tracing-opentelemetry` currently depends on `tonic` 0.11. Would be nice if it could be used with the latest `tonic`.

**Comment by davidB** [comment]
tonic-tracing-opentelemetry 0.20.0 released with tonic 0.12

**Comment by nshalman** [comment]
Thank you!
