### ISSUE TITLE
is it necessary to use `#[instrument]`?

### ISSUE THREAD

**Issue by gitmalong** [davidB/tracing-opentelemetry-instrumentation-sdk#157]
I don't get any traces from the server layer with latest tonic (trace export of other things in my app work wel). Do I additionally need to use `#[instrument(skip_all)]` similar as seen in the exampe?

**Comment by davidB** [comment]
no you use `#|instrument(...)]` to create child span. you could have multiple causes, depending on how you configure it. Can you share more information (configuration code, `OTEL_...` env variable, log level, startup logs) or create a minimal sample reproducing your case?

**Comment by lcmgh** [comment]
Thanks for the troubleshoot section. I still cannot get it working but maybe the info from the first answer below can help.


#### check you only have a single version of opentelemtry (could be part of your CI/build), use cargo-deny or cargo tree

> % cargo tree -i opentelemetry_api
error: package ID specification `opentelemetry_api` did not match any packages

        Did you mean `opentelemetry_sdk`?

I checked another thing:
```bash
cargo tree | grep opentelemetry
│   ├── opentelemetry v0.24.0
│   ├── opentelemetry-http v0.13.0
│   │   ├── opentelemetry v0.24.0 (*)
│   ├── opentelemetry-otlp v0.17.0
│   │   ├── opentelemetry v0.24.0 (*)
│   │   ├── opentelemetry-http v0.13.0 (*)
│   │   ├── opentelemetry-proto v0.7.0
│   │   │   ├── opentelemetry v0.24.0 (*)
│   │   │   ├── opentelemetry_sdk v0.24.1
│   │   │   │   ├── opentelemetry v0.24.0 (*)
│   │   ├── opentelemetry_sdk v0.24.1 (*)
│   ├── opentelemetry-semantic-conventions v0.16.0
│   ├── opentelemetry_sdk v0.24.1 (*)
│   ├── tracing-opentelemetry v0.25.0
│   │   ├── opentelemetry v0.24.0 (*)
│   │   ├── opentelemetry_sdk v0.24.1 (*)
├── tonic-tracing-opentelemetry v0.21.1
│   ├── opentelemetry v0.25.0
│   ├── tracing-opentelemetry v0.26.0
│   │   ├── opentelemetry v0.25.0 (*)
│   │   ├── opentelemetry_sdk v0.25.0
│   │   │   ├── opentelemetry v0.25.0 (*)
│   └── tracing-opentelemetry-instrumentation-sdk v0.21.0
│       ├── opentelemetry v0.25.0 (*)
│       └── tracing-opentelemetry v0.26.0 (*)
```

#### check the code of your exporter and the integration with tracing (as subscriber's layer)
This works as other spans in my app are exported.


```rust
/// Creates an default OpenTelemetry OTLP tracer
///
/// Sets service name and version according to the project's `Cargo.toml`
pub fn create_otlp_tracer(
    config: InitOtlpTracerInput,
) -> Result<opentelemetry_sdk::trace::TracerProvider, TraceError> {
    global::set_text_map_propagator(TraceContextPropagator::new());
    let mut map = HashMap::new();
    map.insert(
        "Authorization".to_string(),
        format!("Api-Token {}", config.auth_token),
    );

    let mut resource = Resource::new(vec![
        KeyValue::new(semcov::resource::SERVICE_NAME, config.service_name),
        KeyValue::new(semcov::resource::SERVICE_VERSION, config.service_version),
    ]);

    resource = resource.merge(&read_dt_metadata());

    opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .http()
                .with_endpoint(config.endpoint)
                .with_headers(map),
        )
        .with_trace_config(
            opentelemetry_sdk::trace::Config::default()
                .with_resource(resource)
                .with_sampler(opentelemetry_sdk::trace::Sampler::AlwaysOn),
        )
        .install_batch(opentelemetry_sdk::runtime::Tokio)
}
```

#### check that log target otel::tracing enable log level trace (or info if you use tracing_level_info feature) to generate span to send to opentelemetry collector.

I used the info feature flag and also set my trace level to `trace`. still no traces from this crate.

**Comment by lcmgh** [comment]
Oh I found it to work now with the latest version

**Comment by davidB** [comment]
You have 2 version of `opentelemetry` (sorry `opentelemery_api` was before some refactor in opentelemetry)
