### ISSUE TITLE
Bump opentelemetry to 0.26

### ISSUE THREAD

**Issue by sengokudaikon** [davidB/tracing-opentelemetry-instrumentation-sdk#169]
Hi, opentelemetry crates in 0.26 depend on tokio any 1. version, which allows to use most recent 1.40 version as opposed to 1.38, This is necessary for crates like surrealdb to work.

**Comment by dpasirst** [comment]
Same issue for me:
024-10-28T11:23:42.798933-06:00 ERROR Flycheck failed to run the following command: CommandHandle { program: "...", arguments: ["check", "--workspace", "--message-format=json-diagnostic-rendered-ansi", "--manifest-path", ".../Cargo.toml", "--keep-going", "--all-targets"], current_dir: Some("...") }, error=Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
    Blocking waiting for file lock on package cache
    Updating crates.io index
error: failed to select a version for `tokio`.
    ... required by package `opentelemetry-otlp v0.25.0`
    ... which satisfies dependency `opentelemetry-otlp = "^0.25"` of package `init-tracing-opentelemetry v0.22.0`
    ... which satisfies dependency `init-tracing-opentelemetry = "^0.22.0"` of package `...`
versions that meet the requirements `~1.38.0` are: 1.38.1, 1.38.0

all possible versions conflict with previously selected packages.

  previously selected package `tokio v1.41.0`

**Comment by davidB** [comment]
version 0.23 released with bump to opentelemetry 0.26.

Re-open the issue if needed
