### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by MidasLamb** [davidB/tracing-opentelemetry-instrumentation-sdk#30]
When running the example with a local OTLP collector the following error is produced after making a request to `/`:
```
OpenTelemetry trace error occurred. Exporter otlp encountered the following error(s): no http client, you must select one from features or provide your own implementation
```

**Comment by MidasLamb** [comment]
I think this is because the example expects some ENV variables to be set before it will run correctly?

**Comment by davidB** [comment]
maybe there are a bug in the default value of the plugin: https://github.com/davidB/axum-tracing-opentelemetry/blob/main/src/tools/otlp.rs

**Comment by fiadliel** [comment]
There's an interesting dichotomy between this library and opentelemetry-otlp. They decided(?) that the protocol would not be selected by an environment variable, but would be a concept captured in the compile-time selection of exporter. It's not clear to me how conscious a decision this was, but I do think that this library and upstream should align on how the protocol is chosen.

(this library uses OTEL_EXPORTER_OTLP_PROTOCOL and OTEL_EXPORTER_OTLP_TRACES_PROTOCOL)

I filed https://github.com/open-telemetry/opentelemetry-rust/issues/909 to ask the OT library developers about it.

**Comment by thedodd** [comment]
On another note, I'm having trouble extracting the propagation context from other services as they call into the service which is using this layer.

The received request does indeed have the expected `uber-trace-id` header with the parent trace/span info (and the propagation is working for other services). However, the spans generated in the code using this layer don't seem to correctly associate with the remote context.

Any thoughts on where the disconnect may be? Looking through the code, it appears as though everything should work correct. I am using the opentelemetry_jaeger extractor as well, to be sure.

**Comment by thedodd** [comment]
Solution: needed to add axum_tracing_opentelemetry=info (or lower) to the tracing env filter `:)`
