### ISSUE TITLE
Make tracer initialization configurable

### ISSUE THREAD

**Issue by cschaible** [davidB/tracing-opentelemetry-instrumentation-sdk#4]
The initialization of the tracer isn't really customizable at the moment.

The function `init_tracer` as shown in the sample application only takes a `CollectorKind` parameter to specify the tracer type. This though isn't really satisfying as the tracer parameters cannot be customized:
```
fn init_tracer(kind: CollectorKind)
```

I've seen that there's the more specific function
```
fn init_tracer_jaeger(resource: Resource)
```
which is called inside the `init_tracer` function, but the `Resource` type isn't sufficient to configure things like the Sampler or the collector endpoint (has to be set on the pipeline).

My solution so far is to copy the content of the `init_tracer_jaeger` function into my own code and configure the tracer there.
It would be better though, if relevant parameters could be configured / overwritten by the user without copying the code.

**Comment by davidB** [comment]
Agree with you, but the purpose of those function was to propose a simple ready to use setup with less configuration as possible (maybe auto detection from environment variable). and to not try duplicate all the possiblity of the opentelemetry api (this lib is not a wrapper).

Anyway I made some refactor to allow to provide a transform function that can modify or fully rewrite a new pipeline. (not documented yet and not published yet).
Can you take a look to the current source code and give me your opinion ?

**Comment by davidB** [comment]
Sorry for late reply I didn't see the notification about the issue.
Thank you for your feedback.

**Comment by davidB** [comment]
the code is part of 0.3.0 (but not documented and no example yet)

**Comment by cschaible** [comment]
I think the API design is good now. It is easy to set the correct service name. 

I guess with "not published yet" you mean that the modules `tools` in `lib.rs` and `jaeger`/`otlp` in `tools/mod.rs` are still private (and you will change that)? If the module visibility of tools/jaeger/otlp will be changed to public a customized jaeger initialization will look really nice:

```
    let tracer = jaeger::init_tracer(
        make_resource(env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION")),
        |p| p.with_agent_endpoint("..."),
    )
    .expect("setup of Tracer")
```

This will provide flexibility as users can either stick to the simple solution as shown in the [example](https://github.com/davidB/axum-tracing-opentelemetry/blob/main/examples/oltp/src/main.rs) or they can customize the specific tracers as needed.

I hope I understood it right. I'm happy to see all the other improvements as well. Thanks for the adjustments.

**Comment by lcmgh** [comment]
Is this init even necessary when there is already a tracer in place (as described here https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/opentelemetry-traces/opentelemetry-ingest/opent-rust)?

**Comment by lcmgh** [comment]
Can confirm this works, see https://github.com/davidB/axum-tracing-opentelemetry/issues/44?notification_referrer_id=NT_kwDOBdi0VbM1NTI2ODE3OTM3Ojk4MDg4MDIx#issuecomment-1421353802 for details why it did not work initially in my case.
