### ISSUE TITLE
Otel field `code.path` is set to `src/middleware/trace_extractor.rs`.

### ISSUE THREAD

**Issue by bradleyess** [davidB/tracing-opentelemetry-instrumentation-sdk#40]
Hey David 👋🏼 

Thanks so much for the wonderful library, and all of your work in the ecosystem generally. I'm grateful!

Perhaps this is PEBCAK, but I had a look through `trace_extractor` and it appears as though `code.path` is not overridden, which results in the trace/span being emitted with the `code.path` being set to the `trace_extractor` rather than say the `src/route.rs`. I hope that makes sense.

Am I missing a way to configure this correctly? Or is this something that's missing right now that you'd be interested in integrating into the library?

Thanks,
Bradley

**Comment by davidB** [comment]
Hi,

I also noticed this issue and it seems to an issue from the tracing or opentelemetry lib (I don't remember, I discussed it with the original author).
If you have a solution I'm interested by this improvement (PR is welcome).
