### ISSUE TITLE
root  Trace span name shown as `<root span not yet received>` 

### ISSUE THREAD

**Issue by ttys3** [davidB/tracing-opentelemetry-instrumentation-sdk#52]
using otlp protocol.

in tempo + grafana (I do not know if jaeger web ui is the same or not),
the "Trace name"  shown as `<root span not yet received>` 

![image](https://user-images.githubusercontent.com/41882455/226357473-57dae027-34f6-416a-ad59-7c1876888b42.png)

it is because `tracing_opentelemetry::OpenTelemetrySpanExt::set_parent(&span, remote_context);`

we can remove this line, but there will be another problem, 

`tracing::info_span!( trace_id = %trace_id )` will not respect the `trace_id` from remote context or we generated at the beginning.

so `set_parent(&span, remote_context)` did resolved the trace_id set issue, but got another problem.

because the remote context is almost a http header, it is very common, it only has trace_id.

as https://docs.honeycomb.io/getting-data-in/tracing/troubleshooting/#your-system-continues-someone-elses-trace said:

> Missing root spans can happen when the trace began outside of your system. It is possible that external requests arrive with a [trace context](https://www.w3.org/TR/trace-context/) header, and your service picks that up and continues the trace.

> In this case, no data is missing. Instead, what should be your root span is referencing a span that you never should receive. Whenever your system receives a request from outside, it should start a new trace.

so, here my issue is:

can we not use `set_parent(&span, remote_context)` , and make the trace_id effective?

**Comment by davidB** [comment]
For a "real" remote trace (aka a trace that comes from incoming http request), IMHO, having "root span not yet received" is the expected behavior. It's translate the reality.
For trace started into the rust app (not from incoming http request), the root span is the one created by the project, so if the app send trace to the same trace collector, we should not have this message. In this case it's a bug.

**Comment by ttys3** [comment]
actully it is the middleware. or we can say it is `tracing` limitation, as I explained.

other framework which also support otel otlp tracing, does not have this issue. like golang echo framework.
we use it on production.

**Comment by ttys3** [comment]
maybe your are using jaeger web UI, it does not show `<root span not yet received>` ?

**Comment by ttys3** [comment]
I compared the behavior with the Golang echo framework middleware implementation: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/labstack/echo/otelecho/echo.go

and also the Rust actix framework middleware implementation: 
https://github.com/OutThereLabs/actix-web-opentelemetry/blob/main/src/middleware/trace.rs

both will not show `<root span not yet received>`  if the client request does not have text propagation headers.

![image](https://user-images.githubusercontent.com/41882455/227793434-101a2c83-3bec-43aa-9b03-dfe76a139a57.png)

so I think I'll make a PR to this middleware.

**Comment by davidB** [comment]
How to find this info, screenshot ?
I don't see it on my Tempo explorer/dashboard

**Comment by ttys3** [comment]
Grafana -> Explore -> Select your `Tempo` source

![image](https://user-images.githubusercontent.com/41882455/228340675-6c0806c9-a70f-4bbc-ae0a-a424872dfe36.png)

**Comment by davidB** [comment]
Should be fixed with 0.12 (and the full rewrite)
