### ISSUE TITLE
Example doesn't work when using protobuf

### ISSUE THREAD

**Issue by hetoug** [davidB/tracing-opentelemetry-instrumentation-sdk#63]
I have tried quite a bit to get the example to work using eg HoneyComb - but without success.
Finally I have tracked it down to a question of whether the protocol is grpc or protobuf, when using a local Jaeger in Docker.
Using grpc works as expected, with the addition of the env var `OTEL_TRACES_SAMPLER=always_on `.

Call:
```
OTEL_TRACES_SAMPLER=always_on OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317" OTEL_SERVICE_NAME=axum-otlp-4317 RUST_LOG="warn,axum_tracing_opentelemetry=info,otel=debug" cargo run
```
and traces appear.

Changing it to:
```
OTEL_TRACES_SAMPLER=always_on OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318" OTEL_SERVICE_NAME=axum-otlp-4318 RUST_LOG="warn,axum_tracing_opentelemetry=info,otel=debug" cargo run
```
This complains about a missing client in the log.

Adding:
```
  opentelemetry-otlp = { version = "=0.11", features = [
    "reqwest-client",
    "reqwest-rustls",
    "http-proto",
    "tls",
  ] }
```
to Cargo.toml removes the missing client error, but still does not let any tracing through to Jaeger.

Any idea what I can do to debug this further?

**Comment by davidB** [comment]
Sorry, I miss your message. Did you find a solution ?

**Comment by davidB** [comment]
With OTLP over gRPC:

```
cd examples/axum-otlp; OTEL_TRACES_SAMPLER=always_on OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="http://localhost:4317" OTEL_SERVICE_NAME=axum-otlp-4317 cargo run
```

I got 1 trace with 2 spans.

But with OTLP over HTTP

- `http://localhost:4318` I got 404 from jaeger
- `http://localhost:4318/v1/traces` I got 1 trace with 1 span or 2 spans in jaeger (1.49)

```
cd examples/axum-otlp; OTEL_TRACES_SAMPLER=always_on OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="http://localhost:4318/v1/traces" OTEL_SERVICE_NAME=axum-otlp-4318 cargo run
```

![image](https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/assets/10675/33a782da-6355-4abc-abd2-b3076c7c22f7)
