### ISSUE TITLE
Please mention that the example on the crate page requires non-default feature flags

### ISSUE THREAD

**Issue by yaleman** [davidB/tracing-opentelemetry-instrumentation-sdk#72]
The example that shows up [here on the crate page](https://crates.io/crates/axum-tracing-opentelemetry) relies on non-default features, and because of that the functions called don't show up in the documentation on docs.rs, and it's incredibly confusing to first-time users of the crate.

**Comment by davidB** [comment]
With version 0.12, I extracted features into their own crate. I guess it will be less confusing for new users.

Thanks for reporting

**Comment by numfin** [comment]
@davidB i'm completely confused on what is happening and why. Instructions very unclear
