### ISSUE TITLE
Set auth headers?

### ISSUE THREAD

**Issue by lostb1t** [davidB/tracing-opentelemetry-instrumentation-sdk#75]
I want to send traces to new relic. But it needs the api key as header in the request. Anyway todo that?

**Comment by davidB** [comment]
Hi,

1. Do you send trace directly from app to new relic or do you have a local (sidecar) collector (agent) ? ([Set up your own app or service with OpenTelemetry | New Relic Documentation](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app/))
2. If you send directly from app to new relic, how to you init your tracer ?

If you build your tracer with `otlp::init_tracer`, according to [opentelemetry\_otlp - Rust](https://docs.rs/opentelemetry-otlp/0.12.0/opentelemetry_otlp/), you can do something like

```
fn setup_newrelic(pipeline: opentelemetry_otlp::OtlpTracePipeline) -> opentelemetry_otlp::OtlpTracePipeline {
    let mut map = MetadataMap::with_capacity(3);
    map.insert("api-key", "my licence");
    pipeline.with_exporter(
            opentelemetry_otlp::new_exporter()
            .tonic()
            .with_endpoint("https://otlp.eu01.nr-data.net:4317")
            .with_timeout(Duration::from_secs(3))
            .with_metadata(map)
         )
}


 let otel_tracer = otlp::init_tracer(otel_rsrc, setup_newrelic)?;
```
