### ISSUE TITLE
trace_id is not being generated automatically

### ISSUE THREAD

**Issue by fhsgoncalves** [davidB/tracing-opentelemetry-instrumentation-sdk#78]
I was using this library on version 0.10.0 and it was working fine, but after I upgraded it to version 0.12.0, it stops sending the traces to datadog.

Investigating the cause, I realize that lots of attributes have changed since 0.10.0, and the `trace_id` field is not being generated automatically anymore.

PS: I'm not using the new crate `init_tracing_opentelemetry` to initialize the tracing + opentelemetry, since the exporter I'm using is `opentelemetry-datadog` instead of `opentelemetry-oltp`.

I can see the `HTTP request` trace being generated in the logs, but it doesn't contain the `trace_id` and `span_id` as before. Example:
```
2023-07-27T02:53:51.476541Z  INFO HTTP request{http.request.method=GET network.protocol.version=1.1 server.address="localhost:8000" user_agent.original="curl/7.88.1" url.path="/some-route" url.scheme="" otel.name=GET otel.kind="Server" http.route="some-route" otel.name="GET /some-route"}
```

I already updated all the related dependencies to also use opentelemetry `0.19` (it was using 0.18 before), but it didn't help.

Any ideas why trace_id and span_id are not being generated?

**Comment by davidB** [comment]
- `span_id` was never generated as attributes of the span
- `trace_id` was removed (in 0.12) from attributes because the value of the attribute could be wrong at generation time (in the axum/http layer), because tracing-opentelemetry subscriber could change/generate a trace_id after creation. The Opentelemetry' span is created on close of the (mirror) tracing'span. And also because I was not able to force a root trace_id (that could be used by tracing-opentelemetry subscriber).

Anyway trace_id and span_id are created but no longer mirror as attributes. It's why you don't see it in log/events.

**Comment by fhsgoncalves** [comment]
Thanks for the quick response!
I saw the removal on version 0.12. 
Is there any way I can do to re-add the trace-id generation for each http trace?

**Comment by fhsgoncalves** [comment]
Or they should not appear on log/events but still be sent to datadog?
If that's the case, there is something else stopping the traces to be sent to datadog with the new version

**Comment by davidB** [comment]
> Or they should not appear on log/events but still be sent to datadog?

Yes

> If that's the case, there is something else stopping the traces to be sent to datadog with the new version

Probably, can you share the setup of the tracer and tracing subscriber ?
Did you also update the exporter crate (eg I had to upgrade zipkin, jaeger,... to be compatible with opentelemetry 0.19) ?
And you should be sure to have only one version of `opentelemetry_api` crate (else several static global are defined). eg at work, I include the command `cargo tree -i opentelemetry_api` in ci (until we have a working setup for cargo deny)

**Comment by fhsgoncalves** [comment]
>Did you also update the exporter crate (eg I had to upgrade zipkin, jaeger,... to be compatible with opentelemetry 0.19) opentelemetry-datadog = "0.7.0" ?

Yes

> And you should be sure to have only one version of opentelemetry_api crate (else several static global are defined). eg at work

Yes, there is just one (v0.19.0)


> can you share the setup of the tracer and tracing subscriber ?

Sure:
```
use std::env;
use std::sync::Arc;
use std::time::Duration;
use tracing::Subscriber;
use tracing_subscriber::registry::LookupSpan;
use tracing_subscriber::{EnvFilter, Layer, Registry};

use crate::infra::telemetry_dd_fmt::DatadogFormatter; // this file is just a copy of this one: https://github.com/Validus-Risk-Management/ddtrace/blob/main/src/formatter.rs

use opentelemetry::global;
use opentelemetry::sdk::trace;
use opentelemetry::sdk::trace::{RandomIdGenerator, Sampler};
use opentelemetry_datadog::{ApiVersion, DatadogPropagator};
use tracing_appender::non_blocking::NonBlocking;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;

fn loglevel_filter_layer(dd_enabled: bool) -> EnvFilter {
    let log_level = std::env::var("RUST_LOG").unwrap_or_else(|_| "info".to_string());
    let dd_log_level = if dd_enabled { "trace" } else { "off" };
    env::set_var(
        "RUST_LOG",
        format!("{log_level},otel::tracing={dd_log_level},otel=debug"),
    );

    EnvFilter::from_default_env()
}

fn log_layer<S>(non_blocking: NonBlocking) -> Box<dyn Layer<S> + Send + Sync + 'static>
where
    S: Subscriber + for<'a> LookupSpan<'a>,
{
    if cfg!(debug_assertions) {
        Box::new(tracing_subscriber::fmt::layer().with_writer(non_blocking))
    } else {
        Box::new(
            tracing_subscriber::fmt::layer()
                .json()
                .event_format(DatadogFormatter)
                .with_writer(non_blocking),
        )
    }
}

fn init_datadog() -> trace::Tracer {
    let service_name = env::var("DD_SERVICE").expect("missing DD_SERVICE");
    let dd_host = env::var("DD_AGENT_HOST").unwrap_or("localhost".to_string());

    // disabling connection reuse with dd-agent to avoid "connection closed from server" errors
    let dd_http_client = reqwest::ClientBuilder::new()
        .pool_idle_timeout(Duration::from_millis(1))
        .build()
        .expect("Could not init datadog http_client");

    let tracer = opentelemetry_datadog::new_pipeline()
        .with_http_client::<reqwest::Client>(Arc::new(dd_http_client))
        .with_service_name(service_name)
        .with_api_version(ApiVersion::Version05)
        .with_agent_endpoint(format!("http://{dd_host}:8126"))
        .with_trace_config(
            trace::config()
                .with_sampler(Sampler::AlwaysOn)
                .with_id_generator(RandomIdGenerator::default()),
        )
        .install_batch(opentelemetry::runtime::Tokio)
        .expect("Could not init datadog!");

    global::set_text_map_propagator(DatadogPropagator::default());

    tracer
}

pub fn init(non_blocking: NonBlocking) {
    let dd_enabled = env::var("DD_ENABLED").map(|s| s == "true").unwrap_or(false);

    let tracer = if dd_enabled {
        Some(init_datadog())
    } else {
        None
    };
    let telemetry_layer = tracer.map(|tracer| tracing_opentelemetry::layer().with_tracer(tracer));

    Registry::default()
        .with(loglevel_filter_layer(dd_enabled))
        .with(log_layer(non_blocking))
        .with(telemetry_layer)
        .init();
}
```

Libs related to opentelemetry and tracing:
```
axum-tracing-opentelemetry = "0.12.0"
opentelemetry = { version = "0.19.0", features = ["rt-tokio", "trace"] }
opentelemetry-datadog = { version = "0.7.0", features = ["reqwest-client"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json", "registry"] }
reqwest-tracing = { version = "0.4.5", features = ["opentelemetry_0_19"] }
```

If you need any more info, just let me know :)

**Comment by fhsgoncalves** [comment]
When I change the RUST_LOG to:
```
info,otel::tracing=info,otel=debug
```
Then the `HTTP request` span is not generated, and the child spans of the request are sent to datadog.

But when the level is trace:
```
trace,otel::tracing=trace,otel=debug
```
Then the `HTTP request` span is generated, but nothing arrives to datadog (neither the child spans).

I guess there is something related to the attributes being generated for that `HTTP request` span... maybe the trace_id, but I'm not sure.

**Comment by davidB** [comment]
Thanks for all those info. Sorry, currently, I don't have any idea :-( . I'll look deeper during the Week-end. If you find the solution, cause please share.

**Comment by davidB** [comment]
@fhsgoncalves, Did you find the cause or a solution? (or an example / test case that I can use to reproduce the issue, I don't have datadog account)

**Comment by fhsgoncalves** [comment]
I could not reproduce the error anymore after the latest version (0.14.1).
I had to change a little bit the log formatter to retrieve the proper trace_id, so datadog can relate logs and traces.
Then now it seems to be fixed and working as expected o/
