### ISSUE TITLE
How to change the log level of http request span events

### ISSUE THREAD

**Issue by alexhumphreys** [davidB/tracing-opentelemetry-instrumentation-sdk#97]
When making requests to the example server as follows
```
cd examples/axum-otlp
cargo run
```
then new terminal
```
curl -i http://127.0.0.1:3003/
```
The opinionated `init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers()` function currently produces log lines like this:
```
    11.876712292s TRACE otel::tracing: close, time.busy: 593µs, time.idle: 202µs
    at tracing-opentelemetry-instrumentation-sdk/src/http/http_server.rs:13 on tokio-runtime-worker
    in otel::tracing::HTTP request with http.request.method: GET, network.protocol.version: 1.1, server.address: "127.0.0.1:3003", user_agent.original: "curl/8.1.2", url.path: "/", url.scheme: "", otel.name: GET, otel.kind: Server, span.type: "web", http.route: "/", otel.name: "GET /", http.response.status_code: 200
```

Is it possible to change the log level of those events from `TRACE` to something else? 

Either by passing a config value, or making a custom version the file [`init-tracing-opentelemetry/srcs/tracing_subscriber_ext.rs`](https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/blob/main/init-tracing-opentelemetry/src/tracing_subscriber_ext.rs)? I went looking around the repo, and found env vars that can be passed to the server to run it like:
```
OTEL_LOG_LEVEL=info OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4317 RUST_LOG=warn,axum_tracing_opentelemetry=info,otel=info cargo run
```
but I think those seem to _filter_ what logs are already being produced, rather than edit the log level of the produced lines.

**Comment by davidB** [comment]
There is no way to change the log level. What is your goal? (the purpose of those log is not to be used as access log)

**Comment by alexhumphreys** [comment]
Ah I was totally thinking it was for access logs 😄 Have you any suggestion on a better approach for access logs?

**Comment by davidB** [comment]
IMHO, create your own middleware (for axum, ...) that will output in the expected format and maybe into a dedicated files.

Maybe I could provide a simple one as part of the axum-tracing crate

**Comment by davidB** [comment]
Also as the example use `init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers()`, the output is not the same between debug and release:

- in debug: output as plain text and log event start and close
- in release: output as json and NO log for event start and close

And the RUST_LOG is no longer `axum_tracing_opentelemetry=info` but `otel::tracing=trace`

**Comment by alexhumphreys** [comment]
> Maybe I could provide a simple one as part of the axum-tracing crate

That'd be cool, but can understand if that's not what you want in the opinionated example. Either way thanks for the middleware suggestion! if you don't add it I'll probably try play around with this idea, would be a good way for me to learn about all this too 👍 

> the output is not the same between debug and release:

Aye i noticed the branching on the build [here](https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/blob/main/init-tracing-opentelemetry/src/tracing_subscriber_ext.rs#L17) with `if cfg!(debug_assertions)`, that was pretty slick.

> And the RUST_LOG is no longer axum_tracing_opentelemetry=info but otel::tracing=trace

Ah, don't think I understood this till now (I'm new to rust 😅), so those are [per module log levels](https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/config_log.html). this I'll play around with a bit more to see the changes.

Think all this answers my initial question anyway, so will close this issue. Thanks!
