### ISSUE TITLE
Status Code as number

### ISSUE THREAD

**Issue by EamonHeffernan** [davidB/tracing-opentelemetry-instrumentation-sdk#99]
In other languages, the official open telemetry packages export the status code of requests as a number, however this package exports them as strings.

This made implementation confusing as it doesn't adhere to the example set by other languages as well as not allowing for checks such as `http.status_code >=200 && http.status_code < 300` to get OK requests after trace collection.

**Comment by davidB** [comment]
Correct, I'll fix it but I would like to also update the label and value for grpc at the same time.

**Comment by davidB** [comment]
should be fixed with version
- 0.14.2 for opentelemetry 0.20
- 0.15.0 for opentelemetry 0.21
